server:
  port: 80
  servlet:
    #项目名，如果不设定，默认是 /
    context-path: /

spring:
  thymeleaf:
    #开发阶段，建议关闭thymeleaf的缓存
    cache: false
    #去掉thymeleaf的严格的模板校验
    mode: LEGACYHTML5
    #设置编码
    encoding: utf-8