server:
  port: 80
#redis基本配置
spring:
  redis:
    host: 192.168.200.7
    # 底层默认值为6379
    port: 6379
    password: ireedtop
    #连接超时时间（毫秒）
    timeout: 600
    jedis:
      pool:
        #连接池最大连接数（负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

  #springSession存放仓库
  session:
    store-type: redis